### ISSUE TITLE
Issues under Mac OS due to System Integrity Protection

### ISSUE THREAD

**Issue by thielul** [picotech/picosdk-python-examples#4]
### Setup

* Example filename: Any
* Version of Python: 2.7
* Pico Technology device model: 2206B
* Driver name and version number: Current
* Operating system: Mac OS X 10.12 and 10.13
* USB port type	(e.g. 2.0): 3.0

### Description
The scripts don't work under newer Mac OS versions, the problem is that the PicoScope libraries cannot be loaded. This is due to System Integrity Protection since El Capitan. Full documentation (with workaround) is [here](http://ulthiel.com/vk2utl/index.php/2017/10/14/picoscope-python-interface-under-mac-os-x/).

**Comment by hsmistry** [comment]
@thielul, thanks for this. 

ps2000a.py and ps4000a.py should be updated to add new products.

**Comment by aarmea-butterfly** [comment]
The workaround unblocks Python usage but breaks PicoScope6.app for me (probably because it invalidates the code signature). I automated a similar fix for [another library here](https://github.com/colinoflynn/pico-python/pull/126) -- the main difference is that this copies the relevant libraries to a temporary directory before patching.

If I get the chance I might port the workaround to this repository too, but the correct fix is for @PicoTechLtd to release a version of PicoScope for macOS that uses absolute paths in its libraries.
